import { jsPDF } from 'jspdf';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import UTIF from 'utif';
import type { PhotoReport, StoredFile } from '../types';
import { dataUrlToUint8, photoFileNameBase } from './helpers';
import { PHOTO_OBJECTIVES } from '../components/PhotoEditor';
import logoUrl from '../assets/sabesp-logo.jpg';
const BLUE=[7,143,190] as const,CYAN=[17,166,204] as const,DARK=[47,59,68] as const,BORDER=[200,208,214] as const,LIGHT=[240,244,246] as const;
const M=10,W=210,BOT=264;let cache:string|null=null;
async function logo(){if(cache)return cache;const b=await fetch(logoUrl).then(r=>r.blob());cache=await new Promise<string>(res=>{const rd=new FileReader();rd.onload=()=>res(String(rd.result));rd.readAsDataURL(b)});return cache}
function wrap(d:jsPDF,t:unknown,w:number){return d.splitTextToSize(String(t??''),w) as string[]}
function header(d:jsPDF,r:PhotoReport,l:string){d.addImage(l,'JPEG',11,10,18,18);d.setFont('helvetica','bold');d.setFontSize(10.8);d.setTextColor(BLUE[0],BLUE[1],BLUE[2]);d.text('RELATÓRIO FOTOGRÁFICO',W/2,17,{align:'center'});d.setFontSize(6.3);d.text('Desenvolvido pelo Polo de Manutenção Suzano - OLMS',W-M,7.2,{align:'right'});d.text('Eng° Eder Nunes',W-M,10.4,{align:'right'});d.setTextColor(DARK[0],DARK[1],DARK[2]);d.setFontSize(7.5);d.text([r.caracterizacao.tipoRelatorio,r.obra.municipio,r.obra.endereco].filter(Boolean).join(' | '),W/2,24,{align:'center',maxWidth:165});d.setDrawColor(CYAN[0],CYAN[1],CYAN[2]);d.setLineWidth(.8);d.line(M,32,W-M,32)}
function sec(d:jsPDF,t:string,y:number){d.setFillColor(BLUE[0],BLUE[1],BLUE[2]);d.roundedRect(M,y,W-2*M,7,1.5,1.5,'F');d.setTextColor(255,255,255);d.setFont('helvetica','bold');d.setFontSize(8.5);d.text(t,M+2,y+4.8);d.setTextColor(DARK[0],DARK[1],DARK[2]);return y+9}
function ensure(d:jsPDF,r:PhotoReport,l:string,y:number,n=15){if(y+n<=BOT)return y;d.addPage();header(d,r,l);return 35}
function table(d:jsPDF,r:PhotoReport,l:string,rows:[string,string][],y:number){for(const[a,b]of rows){const lines=wrap(d,b||'-',120),h=Math.max(4.2,lines.length*2.25+1.8);y=ensure(d,r,l,y,h);d.setDrawColor(BORDER[0],BORDER[1],BORDER[2]);d.setLineWidth(.1);d.setFillColor(LIGHT[0],LIGHT[1],LIGHT[2]);d.rect(M,y,62,h,'FD');d.setFillColor(255,255,255);d.rect(M+62,y,W-2*M-62,h,'FD');d.setFontSize(6.5);d.setFont('helvetica','bold');d.text(a,M+2,y+3,{maxWidth:58});d.setFont('helvetica','normal');d.text(lines,M+64,y+3,{maxWidth:W-2*M-66});y+=h}return y+2}
function para(d:jsPDF,r:PhotoReport,l:string,t:string,y:number){const lines=wrap(d,t,W-2*M-4),h=lines.length*3.4+5;y=ensure(d,r,l,y,h);d.setDrawColor(BORDER[0],BORDER[1],BORDER[2]);d.rect(M,y,W-2*M,h);d.setFont('helvetica','normal');d.setFontSize(7.2);d.text(lines,M+2,y+4.2);return y+h+3}
function size(url:string):Promise<{width:number;height:number}>{return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res({width:i.naturalWidth,height:i.naturalHeight});i.onerror=rej;i.src=url})}
async function fit(d:jsPDF,url:string,x:number,y:number,w:number,h:number){const s=await size(url),k=Math.min(w/s.width,h/s.height),dw=s.width*k,dh=s.height*k;d.addImage(url,url.startsWith('data:image/png')?'PNG':'JPEG',x+(w-dw)/2,y+(h-dh)/2,dw,dh,undefined,'FAST')}
async function tiff(f:StoredFile){const bytes=dataUrlToUint8(f.data),buf=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),ifds=UTIF.decode(buf),out:string[]=[];for(const ifd of ifds){UTIF.decodeImage(buf,ifd);const rgba=UTIF.toRGBA8(ifd),c=document.createElement('canvas');c.width=ifd.width;c.height=ifd.height;const ctx=c.getContext('2d');if(!ctx)continue;ctx.putImageData(new ImageData(new Uint8ClampedArray(rgba),ifd.width,ifd.height),0,0);out.push(c.toDataURL('image/jpeg',.92))}return out}
async function base(r:PhotoReport){const l=await logo(),d=new jsPDF({unit:'mm',format:'a4',compress:true});header(d,r,l);let y=sec(d,'1. Caracterização do relatório',35);y=table(d,r,l,[['Tipo de relatório',r.caracterizacao.tipoRelatorio],['Informação complementar',r.caracterizacao.informacaoComplementar]],y);y=sec(d,'2. Objetivo',ensure(d,r,l,y,25));y=para(d,r,l,PHOTO_OBJECTIVES[r.caracterizacao.tipoRelatorio]||'',y);y=sec(d,'3. Identificação do responsável pela elaboração do relatório',ensure(d,r,l,y,30));y=table(d,r,l,[['Elaborado por',r.responsavel.elaboradoPor],['Data',r.responsavel.data?new Date(r.responsavel.data+'T12:00:00').toLocaleDateString('pt-BR'):''],['Matrícula',r.responsavel.matricula],['Cargo/Função',r.responsavel.cargo],['Empresa',r.responsavel.empresa]],y);y=sec(d,'4. Dados da Obra',ensure(d,r,l,y,35));y=table(d,r,l,[['Município',r.obra.municipio],['Endereço',r.obra.endereco],['Tipo de Serviço',r.obra.tipoObra],['Água/Esgoto',r.obra.aguaEsgoto],['Empresa Executora',r.obra.empresaExecutora],['Contrato',r.obra.contrato],['Descrição complementar',r.obra.descricaoComplementar]],y);if(r.observacoesGerais){y=sec(d,'5. Observações gerais da vistoria',ensure(d,r,l,y,20));y=para(d,r,l,r.observacoesGerais,y)}for(let i=0;i<r.fotos.length;i++){const f=r.fotos[i];d.addPage();header(d,r,l);let py=sec(d,`Foto ${i+1}: ${f.titulo}`,35);if(f.descricao)py=para(d,r,l,f.descricao,py);if(f.imagem)await fit(d,f.imagem.data,M+2,py+2,W-2*M-4,BOT-py-4)}for(let ai=0;ai<r.anexos.length;ai++){const a=r.anexos[ai];if(/pdf/i.test(a.type)||/\.pdf$/i.test(a.name))continue;const pages=/tiff?/i.test(a.type)||/\.tiff?$/i.test(a.name)?await tiff(a):[a.data];for(let pi=0;pi<pages.length;pi++){d.addPage();header(d,r,l);let ay=sec(d,`Anexo ${ai+1}${pages.length>1?` - ${pi+1} de ${pages.length}`:''}`,35);if(pi===0&&a.descricao)ay=para(d,r,l,a.descricao,ay);await fit(d,pages[pi],M+2,ay+2,W-2*M-4,BOT-ay-4)}}return d.output('arraybuffer')}
async function merge(base:ArrayBuffer,r:PhotoReport){const out=await PDFDocument.load(base),bold=await out.embedFont(StandardFonts.HelveticaBold),font=await out.embedFont(StandardFonts.Helvetica);for(let ai=0;ai<r.anexos.length;ai++){const a=r.anexos[ai];if(!(/pdf/i.test(a.type)||/\.pdf$/i.test(a.name)))continue;try{const bytes=dataUrlToUint8(a.data),ext=await PDFDocument.load(bytes),pages=await out.embedPdf(bytes,ext.getPageIndices());for(let pi=0;pi<pages.length;pi++){const p=out.addPage([595.28,841.89]),e=pages[pi],scale=Math.min(535/e.width,700/e.height),dw=e.width*scale,dh=e.height*scale;p.drawRectangle({x:28,y:775,width:539,height:20,color:rgb(BLUE[0]/255,BLUE[1]/255,BLUE[2]/255)});p.drawText(`Anexo ${ai+1} - ${pi+1} de ${pages.length}`,{x:35,y:781,size:8,font:bold,color:rgb(1,1,1)});if(a.descricao)p.drawText(`Descrição: ${a.descricao}`.slice(0,150),{x:28,y:760,size:6.5,font});p.drawPage(e,{x:(595.28-dw)/2,y:45+(700-dh)/2,width:dw,height:dh})}}catch(e){console.warn(e)}}return out}
async function stamp(p:PDFDocument){const f=await p.embedFont(StandardFonts.Helvetica),c=rgb(CYAN[0]/255,CYAN[1]/255,CYAN[2]/255),ps=p.getPages();ps.forEach((x,i)=>{const{width}=x.getSize();x.drawLine({start:{x:28,y:39},end:{x:width-28,y:39},thickness:.45,color:c});['Companhia de Saneamento Básico do Estado de São Paulo - Sabesp','Divisão de Manutenção e Serviços Operacionais Suzano - OLMS','Rua Benjamin Constant 1980 - Centro | CEP 08674-179 | Suzano - SP','www.sabesp.com.br'].forEach((t,j)=>x.drawText(t,{x:28,y:30-j*6,size:5.2,font:f,color:c}));x.drawText(`${i+1} de ${ps.length}`,{x:width-58,y:13,size:6.2,font:f,color:c})})}
export async function generatePhotoPdf(r:PhotoReport){const b=await base(r),p=await merge(b,r);await stamp(p);const bytes=await p.save({useObjectStreams:true}),blob=new Blob([bytes as unknown as BlobPart],{type:'application/pdf'});return{blob,url:URL.createObjectURL(blob),fileName:`${photoFileNameBase(r)}.pdf`}}
